### ISSUE TITLE
Part 1.1: Explore New Feeds

### ISSUE THREAD

**Issue by ykomal** [Egnite-git/ds-python-du-ankithsavio#1]

**Comment by ankithsavio** [comment]
I will be using RSS feed from the following
https://data-science-blog.com/
https://dataconomy.com/
https://statisfaction.wordpress.com/
http://statswithcats.wordpress.com/
http://www.tatvic.com/blog/
http://www.johndcook.com/blog/
https://databricks.com/blog/
https://data-flair.training/
https://hevodata.com/blog/
https://www.datarobot.com/blog/
https://www.trifacta.com/
https://www.thedataincubator.com/
https://indatalabs.com/blog/
https://nycdatascience.com/blog/
https://predictivehacks.com/
https://datamites.com/blog/
https://appsilon.com/data-for-good/
https://data-science-blog.com/en/
https://www.theseattledataguy.com/
https://www.datascienceish.net/
https://analyticstrategy.com/
http://www.thejuliagroup.com/blog/
https://algobeans.com/
https://arilamstein.com/blog/
http://bigdatatobigprofits.com/
https://practicalanalytics.wordpress.com/
http://blog.cluster-text.com/
http://cooldata.wordpress.com/
https://www.data-blogger.com/
https://www.verramobility.com/
http://blogs.forrester.com/category/big_data
https://www.ibm.com/blogs/journey-to-ai/
https://www.kdnuggets.com/
https://www.r-bloggers.com/
https://blogs.sas.com/content/
https://www.smartdatacollective.com/
https://starbridgepartners.com/
https://blueorange.digital/
https://www.9to5sas.com/
https://aryng.com/blog/
https://anyinstructor.com/
https://analytixon.com/
https://neuralmarkettrends.com/
https://www.dataversity.net/category/data-topics/data-science-data-topics/
https://www.remixinstitute.com/
https://mlwhiz.com/
https://ischoolonline.berkeley.edu/blog/
https://www.datascienceassn.org/blog/
https://datamahadev.com/
https://towardsdatascience.com/
http://fivethirtyeight.com/
https://dimensionless.in/blog/
https://insightextractor.com/
https://blog.zhaw.ch/datascience/
https://matloff.wordpress.com/
https://blog.socratesk.com/
http://datadscllc.com/
https://datascience.codata.org/
https://carlocarandang.com/
https://www.datascienceforsocialgood.org/
https://buckwoody.wordpress.com/
https://erdatadoc.com/
https://dataelixir.com/
https://dsianalytics.com/insights/
https://ryanswanstrom.com/datascience101/
https://win-vector.com/
https://dataaspirant.com/
https://datascience.smu.edu/
https://xianblog.wordpress.com/
http://www.datagenetics.com/blog
http://www.dataquest.io/blog/
http://www.freakonomics.com/blog/
https://www.eminenture.com/blog/
http://fbhalper.wordpress.com/
http://www.ibmbigdatahub.com/blog
http://www.informationisbeautiful.net/blog/
http://www.insightdatascience.com/blog/
https://jmanton.wordpress.com/
https://justindomke.wordpress.com/
https://www.insightdata.co.uk/
http://compbio.ucsd.edu/outreach/data-science-blog/
https://ujjwalkarn.me/
https://cds.nyu.edu/
http://learninglover.com/blog/
https://lovestats.wordpress.com/
http://machinelearningmastery.com/blog/
http://www.predictiveanalyticsworld.com/blog/
http://shapeofdata.wordpress.com/
http://www.svds.com/
https://www.analyticsvidhya.com/
