### ISSUE TITLE
Part 2.1: Extract Data Attributes

### ISSUE THREAD

**Issue by ykomal** [Egnite-git/ds-python-du-ankithsavio#5]

**Comment by ankithsavio** [comment]
https://github.com/Egnite-git/ds-python-du-ankithsavio/blob/964baebec80be182bdf5eb3329e85d66e3846f26/week-2/RSS%20XML%20feed%20extraction.ipynb

https://github.com/Egnite-git/ds-python-du-ankithsavio/blob/main/week-2/final_data.csv
